name: drive_time
description: A new Flutter application.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_support_pack: ^0.0.5+1
  package_info: ^0.4.3+2
  stacked: ^1.7.7
  provider: ^4.3.2+3
  get_it: ^5.0.3
  rxdart: ^0.25.0
  cupertino_icons: ^1.0.0
  auto_route: ^0.6.9
  intl: ^0.16.1
  flutter_rating_bar: ^3.2.0+1
  reactive_forms: ^7.6.2
  platform_date_picker: ^0.0.4+1
  r_dart_library:
    git:
      url: https://github.com/YK-Unit/r_dart_library.git
      ref: 0.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.6.10
  build_runner: ^1.10.11
flutter:
  uses-material-design: true
  fonts:
  - family: SFProDisplay
    fonts:
    - asset: packages/drive_time/assets/fonts/SFProDisplay/SFProDisplay-Black.otf
    - asset: packages/drive_time/assets/fonts/SFProDisplay/SFProDisplay-Bold.otf
    - asset: packages/drive_time/assets/fonts/SFProDisplay/SFProDisplay-Heavy.otf
    - asset: packages/drive_time/assets/fonts/SFProDisplay/SFProDisplay-Light.otf
    - asset: packages/drive_time/assets/fonts/SFProDisplay/SFProDisplay-Medium.otf
    - asset: packages/drive_time/assets/fonts/SFProDisplay/SFProDisplay-Regular.otf
    - asset: packages/drive_time/assets/fonts/SFProDisplay/SFProDisplay-Semibold.otf
    - asset: packages/drive_time/assets/fonts/SFProDisplay/SFProDisplay-Thin.otf
    - asset: packages/drive_time/assets/fonts/SFProDisplay/SFProDisplay-Ultralight.otf
  assets:
  - packages/drive_time/assets/images/dashboard/ic_end.png
  - packages/drive_time/assets/images/dashboard/ic_rest.png
  - packages/drive_time/assets/images/dashboard/ic_start.png
  - packages/drive_time/assets/images/dashboard/ic_work.png
  - packages/drive_time/assets/images/main/ic_book.png
flr:
  core_version: 3.1.0
  dartfmt_line_length: 80
  assets:
  - lib/assets/images
  fonts:
  - lib/assets/fonts
